### ISSUE TITLE
Tailwindcss 미적용

### ISSUE THREAD

**Issue by Yallu201** [Yallu201/react-settlement-template#1]
tailwindcss는 디자이너와 협업하며 신규 컴포넌트를 생성하는 목적으로서 사용하면 유용한 패키지입니다.

아래 링크는 kakao의 emotion => tailwindcss 전환기를 확인할 수 있는데요
https://fe-developers.kakaoent.com/2022/221013-tailwind-and-design-system/

위 글에서 명시한 이유는 아래와 같습니다.
`커스텀 플러그인 추가하기`
`다해상도 대응`
`새로운 단위 정의하기`
`컬러모드 지원`

어드민 목적으로 이용하는 경우, 복잡하고 다양한 스타일링이 필요하기보다는, mui의 컴포넌트를 활용하고, 필요하다면 간단한 스타일링 적용하는 방향이 어드민 개발방향에 더 잘 맞다고 판단하였습니다.

해당 템플릿을 사용하여 디자이너와 협업하여 신규컴포넌트를 사용하는 등 tailwindcss를 통해 시스템을 구축하는 방향이 이점이 더 많게되었을 때 적용한다면 좋을 것 같습니다.

**Comment by Opti-kjh** [comment]
@Yallu201 
제 생각도 동일합니다.
일반적인 웹서비스와 다르게 어드민의 경우 정형화된 컴포넌트를 구축하고 예외의 형태가 필요한 경우가 빈번하게 일어나지 않기 때문에 tailwindcss는 굳이 써야할까? 라는 의문이 있었어요.
관련해서 위 내용과 같이 진행하는걸로 하시죠 👍🏿

**Comment by Yallu201** [comment]
@Opti-kjh 넵 좋습니다!
