### ISSUE TITLE
.env 불필요 환경변수 제거

### ISSUE THREAD

**Issue by chocochoi** [Yallu201/react-settlement-template#2]
.env 파일들에서 불필요한 환경변수 제거
템플릿으로 사용될것이기 때문에 기존 nimda에서 사용하면 api 환경변수를 제거하면 좋을거같습니다
![스크린샷 2024-03-21 오전 10 55 09](https://github.com/Yallu201/react-ag-grid-template/assets/52714501/8626c58d-e761-4cc6-b320-f7f9253039eb)

`src/constants/env.ts`
에서도 제거해주면 좋을거같습니다~!

**Comment by Yallu201** [comment]
@chocochoi 불필요한 환경변수는 제거하였습니다~
